### ISSUE TITLE
Windows 2003 server

### ISSUE THREAD

**Issue by shrawanikarpe** [arago/hiro-winrm-actionhandler#5]
Hi Marcus,

can you tell if you have tried this method in windows 2003 I am facing some issue after following the document.
For different 2003 server, I am getting different error response 

Command execution failed:
the specified credentials were rejected by the server

Command execution failed:
Bad HTTP response returned from server. Code 400

**Comment by mklemm2** [comment]
Kerberos message encryption is currently not supported for Windows Server 2003 (see <https://github.com/02strich/pykerberos/issues/36>). Added parameter MessageEncryption to `winrm-actionhandler.yaml` to disable it.

**Comment by mklemm2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [hello](https://trello.com/c/oTydatJJ/1-hello)
